name: Run script

on:
  schedule:
    # - cron: '*/5 * * * *'
    # 表达式生成  https://crontab.guru/
    - cron: '0 */24 * * *'

  workflow_dispatch: {}

jobs:
  build:
    name: Run script
    runs-on: ubuntu-latest

    env:
      ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checking out Repository
        uses: actions/checkout@master

      - name: Setting up node.js
        uses: actions/setup-node@v5.0.0
        with:
          node-version: '22.20.0'

      - name: Setting up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.17.0

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Installing dependencies
        run: pnpm install

      - name: Run script
        run: pnpm run start

